### ISSUE TITLE
Question: use Gutenberg with Settings model

### ISSUE THREAD

**Issue by vosco88** [FlusherDock1/Gutenberg#15]
Hi I am wondering would it be possible to use Gutenberg editor with OctoberCMS Settings model? 
My use case is that in the settings of my plugin I want to provide user with ability to create kind of a one page with these blocks,
I tried to add it to my Settings model and then extending the System Settings controller with the behaviour but I am not able to work it out. 
So I am thinking if something like this is possible or how could I do it?

Thank you

**Comment by FlusherDock1** [comment]
As long as model extends standard OctoberCMS Model class, i don't see any problem why it shouldn't.
