### ISSUE TITLE
News On StaticPages Integration

### ISSUE THREAD

**Issue by Elidrake** [FlusherDock1/Gutenberg#16]
Just curious if there is any news on StaticPages Integration.  If it's been put on ice, I would like to tackle it.

**Comment by Elidrake** [comment]
Ah, I just noticed your TODO in the Extenders.  If I don't hear back on this by Monday, I'll close this out and put together a pull request to finish that off.  Thanks for the awesome plugin either way!

**Comment by PubliAlex** [comment]
Nice to hear :)
