### ISSUE TITLE
Setup Issue 

### ISSUE THREAD

**Issue by Ultrapraise** [FlusherDock1/Gutenberg#17]
Hi, 

Great Plugin.
Works perfectly well until I noticed embedded media and videos weren't saving, So I went through the installation guide again and saw I didn't Implement it, after adding the behavior in $implement array I get this error from existing posts:

"Trying to get property 'contentable_id' of non-object" on line 96 of /home/xxxxx/public_html/vendor/october/rain/src/Database/Relations/MorphOne.php

and the editor looks all messed up and un-arraigned.

What could I have done wrong?

Here are my codes:

```
<?php namespace RainLab\Blog\Models;

use Db;
use Url;
use App;
use Str;
use Html;
use Lang;
use Model;
use Markdown;
use BackendAuth;
use ValidationException;
use Backend\Models\User;
use Carbon\Carbon;
use Cms\Classes\Page as CmsPage;
use Cms\Classes\Theme;
use Cms\Classes\Controller;
use RainLab\Blog\Classes\TagProcessor;

/**
 * Class Post
 */
class Post extends Model
{
    use \October\Rain\Database\Traits\Validation;

    public $table = 'rainlab_blog_posts';
    public $implement = [
        '@RainLab.Translate.Behaviors.TranslatableModel',
        'ReaZzon.Gutenberg.Behaviors.Gutenbergable'
    ];
    // ...
}
```

and

```
<?php namespace RainLab\Blog\Controllers;

use BackendMenu;
use Flash;
use Lang;
use Backend\Classes\Controller;
use RainLab\Blog\Models\Post;

class Posts extends Controller
{
    public $implement = [
        'Backend.Behaviors.FormController',
        'Backend.Behaviors.ListController',
        'Backend.Behaviors.ImportExportController',
        'ReaZzon.Gutenberg.Behaviors.GutenbergController'
    ];
```

**Comment by FlusherDock1** [comment]
Hi! What columns do you have in your Post model? Do you have "content" column?

**Comment by Ultrapraise** [comment]
It works fine now with the html embed,
I guess we will make use of it like that.

**Comment by chiragkanjariya** [comment]
getting same for custom plugin
