### ISSUE TITLE
create new content

### ISSUE THREAD

**Issue by silencevenus** [FlusherDock1/Gutenberg#19]
when I try to create one model, which implements with **ReaZzon.Gutenberg.Behaviors.Gutenbergable** and controller with **ReaZzon.Gutenberg.Behaviors.GutenbergController**
but it showed the error message 

`"SQLSTATE[HY000]: General error: 1364 Field 'contentable_id' doesn't have a default value (SQL: insert into `reazzon_gutenberg_contents` (`raw_content`, `rendered_content`, `updated_at`, `created_at`) values (
<p>wqerqewr</p>

<p>qwer</p>

<p>qwer</p>
, 
<p>wqerqewr</p>

<p>qwer</p>

<p>qwer</p>
, 2019-10-31 12:45:20, 2019-10-31 12:45:20))" on line 664 of /var/www/html/edm/vendor/laravel/framework/src/Illuminate/Database/Connection.php

`

**Comment by FlusherDock1** [comment]
Can you write your steps to reproduce this error? 

I just did fresh install with Gutenberg from marketplace, and created plugin with Builder, and everything works fine for me.
