### ISSUE TITLE
Rainlab.Blog integration

### ISSUE THREAD

**Issue by vosco88** [FlusherDock1/Gutenberg#2]
Hi I just want to check if I did the Rainlab.Blog integration right, I've added the necessary classes.
This is the result I am getting so I wanted to check if it is right - orange background and still visible original editor. 

![image](https://user-images.githubusercontent.com/14372933/57986723-f8c78400-7a78-11e9-846e-71591a537f80.png)

Also when trying to save I am getting this error
`"SQLSTATE[HY000]: General error: 1364 Field 'contentable_id' doesn't have a default value (SQL: insert into `reazzon_gutenberg_contents` (`raw_content`, `rendered_content`, `updated_at`, `created_at`) values (, , 2019-05-19 20:59:41, 2019-05-19 20:59:41))" on line 664 of C:\laragon\www\tmavaochutnavka\vendor\laravel\framework\src\Illuminate\Database\Connection.php`

And last question if I would like to have Slovak translation I should help translating also VanOns/laraberg right?

**Comment by FlusherDock1** [comment]
You don't need to add something to RainLab.Blog plugin manually. 
Just install Blog and Gutenberg, find in settings Gutenberg tab, and click on Gutenberg settings. Then just click to RainLab.Blog Integration switch, and you are done.

**Comment by FlusherDock1** [comment]
![image](https://user-images.githubusercontent.com/20070837/58019336-f6fbd000-7b0d-11e9-93e6-11437e91411f.png)

**Comment by vosco88** [comment]
Thanks I missed that there is a settings for Gutenberg.

**Comment by FlusherDock1** [comment]
When you use integration, you don't need to change anything, just use RainLab.Blog as usual, so if you want to render content, just call {{ post.content_html|raw }} as stock RainLab.Blog Post component do.
