### ISSUE TITLE
Integrate with Indikator.News

### ISSUE THREAD

**Issue by Fenn-CS** [FlusherDock1/Gutenberg#20]
The [Indikator, News and Newsletter plugin](https://octobercms.com/plugin/indikator-news) is one of the top blogging plugins for OctoberCMS it's important that this cool import from WordPress is present there.

**Comment by FlusherDock1** [comment]
I think that can be done in next updates 👍

**Comment by Fenn-CS** [comment]
Thanks! [this commit](https://github.com/FlusherDock1/Gutenberg/commit/92ca8ffecaab6a92d2ca54bd63eb678db9947937) would have to be referenced and added to the Indikator.News documentation so devs can start trying it out.

**Comment by gergo85** [comment]
Thank you for support the Indikator.News plugin! :)
