### ISSUE TITLE
Error when saving post

### ISSUE THREAD

**Issue by kombimedia** [FlusherDock1/Gutenberg#23]
Hi there,

I have setup the Rainlab Blog and Gutenberg plugins on a fresh install of October and am getting an SQL error when trying to save a new blog post.

`PDOException: SQLSTATE[HY000]: General error: 1364 Field 'contentable_id' doesn't have a default value in /Users/responsive/Documents/MAMP-Sites/octobergutenberg/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105 `

- System build is 461.
- Blog version is 1.4.0.
- Gutenberg version 1.2.5

Any ideas on what may be causing this error?

Cheers,

Cy

**Comment by movetonull** [comment]
Hi, 
I also got this error when I save, but I did not get this error when updating.
I think this plugin is trying to save its model before the main model.
![image](https://user-images.githubusercontent.com/5135513/70998121-5f3c7f80-20f8-11ea-86cf-0754eb6f5652.png)

**Comment by FlusherDock1** [comment]
This happeinin due your model is not created yet, and gutenberg tryung to save content with non-existing model. 

I also get this error, but eventually after cleaning cache and doing exactly nothing, it's disappeared. 
I don't know what exactly causing this problem, but i will look into it. Will close this issue by now.

**Comment by chiragkanjariya** [comment]
i'm getting same while saving data

**Comment by chiragkanjariya** [comment]
![image](https://user-images.githubusercontent.com/17644894/88251934-12daa300-ccca-11ea-8127-5b6904815942.png)
![image](https://user-images.githubusercontent.com/17644894/88251957-284fcd00-ccca-11ea-8fb7-e0b162def80e.png)
