### ISSUE TITLE
Full screen mode not working!

### ISSUE THREAD

**Issue by Fenn-CS** [FlusherDock1/Gutenberg#27]
In OctoberCMS, the editors are usually embeded within small portions of the page, other Wysiwigs can get full screen(using up all browser screen like a word processor) however, Full screen mode for this editor only tries to take the available within the container in which it finds itself. This behavior is not desirable.

![fullscreen-mode](https://user-images.githubusercontent.com/14317775/75702367-a4af2880-5cb5-11ea-8d9d-bb1120b7650c.png)

**Comment by FlusherDock1** [comment]
Fixed [6884056](https://github.com/FlusherDock1/Gutenberg/commit/6884056dae134a264eb400fa49e76e7c23dbb553)

**Comment by Fenn-CS** [comment]
Thanks, cheers!
