### ISSUE TITLE
As frontend component

### ISSUE THREAD

**Issue by chrisvidal** [FlusherDock1/Gutenberg#3]
Would that be possible to integrate this editor as a frontend component?

**Comment by SebastiaanKloos** [comment]
@chrisvidal like rendering the content on the frontend or do you want to use the editor on the frontend?

**Comment by chrisvidal** [comment]
I want to use the editor in the frontend

**Comment by FlusherDock1** [comment]
I think you need to use somewhat of second party plugins of backend formwidgets on frontend to do that.

**Comment by SebastiaanKloos** [comment]
@FlusherDock1 that is an option or create a component for the editor to use on the frontend

**Comment by chrisvidal** [comment]
yes, like @SebastiaanKloos is saying, I was thinking to be able to use a component that integrates Gutenberg. taht would be awesome

**Comment by FlusherDock1** [comment]
The original Gutenberg.js still have tons of bugs, so I'm limited, and I can't easily add that awesome features.

For example, you can't implement multiple editors on the same page. So I see already a lot of problems with it. Imagine the situation when I solved all the errors and the original repository is updated the next day. All my work immediately goes down the drain.
