### ISSUE TITLE
gutenburg wont display in blog

### ISSUE THREAD

**Issue by raskrial** [FlusherDock1/Gutenberg#31]
hi, i just updated gutenburg to version 1.3 and now it wont display at all in rainlab blog while following instruction for installation. version 1.2.5 was working before. Thx to help me with this.

**Comment by renickbuettner** [comment]
I also have this bug :o I reinstalled all plugins, but it's just white space

**Comment by HitArrowLegend** [comment]
Same here

**Comment by FlusherDock1** [comment]
Will investigate about this bug in near days.

**Comment by rebaz88** [comment]
same here

**Comment by FlusherDock1** [comment]
Fixed in 1.3.1. Update via OctoberCMS settings.

**Comment by rebaz88** [comment]
Thank you very much. It works
