### ISSUE TITLE
Conflict with TailwindCSS developped themes

### ISSUE THREAD

**Issue by RomainMazB** [FlusherDock1/Gutenberg#32]
[EDIT] Found an easy way to fix this issue, but you should modify the README to prevent others who use Tailwind:
Basicaly I just ensure my `theme.css` is the last file which is included placing the {% styles %} tag before it in my layout.htm:
```html
<!-- Scripts & Styles-->
{% styles %}
<link rel="stylesheet" property="stylesheet" href="{{ 'assets/css/theme.css'|theme }}">
```

Hi!

First, thanks for the work, this is much appreciated to convince customers who came with a WP website and are reticent to migrate.

I've been using the plugin in RainLab.Blog with a theme I've developed myself and ended in a weird bug only in blogPost component: my head is hidden.

I've discovered that it was due to the import of the plugin's CSS styles, which overrides the Tailwind's one:
![Capture d’écran de 2020-05-07 21-50-37](https://user-images.githubusercontent.com/53976837/81338423-e771f000-90ac-11ea-8dc9-ba520d5deb9a.png)

To reproduce I guess you just have to create a basic page, include Tailwind and Laraberg.css and create a block with responsive tailwind style:
```html
<div class="hidden lg:block">This block should only appears for lg breakpoint and upper</div>
```
This kind of issue should also appear with Bootstrap, Bulma

I want to investigate further but I'm afraid the only way to fix this issue will end in a breaking change: prefix all the laraberg content style so it won't override the "global" style and will only be applied when we explicity want it.

Something like:
```html
==
function onStart()
{
    $this->addCss('/plugins/reazzon/gutenberg/assets/laraberg.min.css');
}
==
        {% set post = __SELF__.post %}
        <h1 class="font-black text-2xl">{{ post.title }}</h1>
        <p class="info">
            Posté
            {% if post.categories.count %} dans
            {% for category in post.categories %}
            <a href="{{ category.url }}">{{ category.name }}</a>{% if not loop.last %}, {% endif %}
            {% endfor %}
            {% endif %}
            le {{ post.published_at|strftime('%e %B %Y') }}
        </p>

        <div class="laraberg-content">{{ post.content_html|raw }}</div>
```
With a laraberg.css like:
```CSS
.laraberg-content .hidden {
    display: none;
}
```
I could also prefix tailwind but... it would be now a much bigger work to modify all my theme's pages, layout, partials... and not a so good idea since it still leave the Gutenberg plugin useless with all the tailwind developed theme in the marketplace.

Do you have any other idea to fix that? Or would you be open to a PR with a breaking change?

**Comment by damsfx** [comment]
@FlusherDock1 
A reply would have been appreciated.
