### ISSUE TITLE
Remove content  change promp on leave page

### ISSUE THREAD

**Issue by chiragsenjaliya** [FlusherDock1/Gutenberg#33]
How to remove events for content change prompt when we leave the page?

I am using Gutenberg form widget in model fields.yaml as a custom type

![image](https://user-images.githubusercontent.com/19857731/81778121-dc391d00-950f-11ea-9506-23d5e3e5e276.png)

**Comment by FlusherDock1** [comment]
I'm sorry @chiragsenjaliya, but this prompt form original Gutenberg package, i just can't disable it.
