### ISSUE TITLE
How to add custom Color Palettes?

### ISSUE THREAD

**Issue by chiragsenjaliya** [FlusherDock1/Gutenberg#34]
Hello,

I am using this plugin and this is an awesome plugin.

I want to add custom color palettes. Is this possible?

**Comment by FlusherDock1** [comment]
Hello, custom color palettes for what specificly?

**Comment by chiragsenjaliya** [comment]
Predefined custom color palette  for font color and background color

**Comment by FlusherDock1** [comment]
This palletes coming from Guitenberg original package. i think you need to rebuild their package...

**Comment by chiragsenjaliya** [comment]
Ok thank you for you reply. Really appreciate it 😊
