### ISSUE TITLE
REQUEST - Composer Installation Support.

### ISSUE THREAD

**Issue by mikestraczek** [FlusherDock1/Gutenberg#4]
Hey,

It's possible to make this plugin for composer installation ready?

Regards
Mike Straczek

**Comment by FlusherDock1** [comment]
Sorry for a long answer, I was very busy.
Yes it is possible, but as I see you just created PR with data for packagist :)
Thanks for your PR.

**Comment by mikestraczek** [comment]
No problem :-) I just want support your great plugin!

**Comment by FlusherDock1** [comment]
Thanks a lot! 
Submitted project to packagist.

https://packagist.org/packages/reazzon/gutenberg
