### ISSUE TITLE
How can I add custom blocks?

### ISSUE THREAD

**Issue by xitara** [FlusherDock1/Gutenberg#8]
Where must I put the code to add custom blocks. I did't find any solution for this problem.

**Comment by FlusherDock1** [comment]
Hello! At the moment there is no convenient API for OctoberCMS. But you can extend it by manually editing gutenberg.js in `/formwidgets/gutenberg/assets/js`. For more information how to add a custom block, read here https://github.com/VanOns/laraberg#custom-blocks
